org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
android.injected.build.api.implementation.type=STANDALONE
org.gradle.configureondemand=false
org.gradle.daemon=false
kotlin.incremental=false
